import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {LayoutWrapper} from "@/components/LayoutWrapper";
import {getTheme, Theme} from "@/constants/colors";
import {Providers} from "@/contexts/Providers";
import {ThemeScript} from "@/contexts/ThemeScript";
import {cookies} from "next/headers";
import React from "react";
import {redirect} from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Bookline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    return (
    <html lang="en" className="dark" >
      <body className={`antialiased dark:bg-black-800`}>
      <ThemeScript />
      <Providers>
          <LayoutWrapper>
              {children}
          </LayoutWrapper>
      </Providers>
      </body>
    </html>
  );
}